df_defs = {'AUS':'Austrailian Dollars',
           'EUR':'Euro',
           'JPY':'Japanese Yen',
           'GBP':'British Pound Sterling',
           'CAD':'Canadian Dollars',
           'CHF':'Swiss Francs',
           'ZAR':'South African Rand',
    }

column_defs = {'Value': 'Price of currency in USD',
               'Value Yesterday': 'Price of currency in USD, prior period',
               'Log Return': 'Log return from the prior period',
               'SandP':'S&P 500 end of day close price',
               'TBill':'10 year Treasury Bill rate',
               'BollingerLower':'Lower bound of the Bollinger Bands',
               'BollingerMiddle':'Middle bound of the Bollinger Bands',
               'BollingerUpper':'Upper bound of the Bollinger Bands',
               'RSI':'Relative strength index',
               'MA10':'10-period moving average',
               'EMA12':'12-period exponential moving average',
               'EMA26':'26-period exponential moving average',
               'MACD':'Moving Average Convergence/Divergence',
              }

column_types = {'Value': 'numeric',
                'Value Yesterday':'numeric',
                'Log Return': 'numeric',
                'SandP':'numeric',
                'TBill':'numeric',
                'BollingerLower':'numeric',
                'BollingerMiddle':'numeric',
                'BollingerUpper':'numeric',
                'RSI':'numeric',
                'MA10':'numeric',
                'EMA12':'numeric',
                'EMA26':'numeric',
                'MACD':'numeric',
               }

column_units = {'Value': 'per USD',
                'Value Yesterday':'per USD, prior period',
                'Log Return': '% return from prior period',
                'SandP':'USD',
                'TBill':'% return',
               }